on:
  push:
    branches:
      - master









jobs:
  build:
    runs-on: ubuntu-latest
  


    steps:
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v

      - name: 'Aftert'
        run: ls
        
        
        
